### PR TITLE
image ratio fixed

### LINKED ISSUE #58: Allow by clicking the chat avatar to see the image in a full size

### PR DESCRIPTION
**Pull request by MosheShlomi**

### CODE REVIEW

File: src/components/Chat/Chat.jsx [hunk 1]
```diff
@@ -266,9 +266,25 @@ const Chat = props => {
                 onClose={closeImgDialog}
                 aria-labelledby="alert-dialog-title"
                 aria-describedby="alert-dialog-description"
-                maxWidth="xl"
+                maxWidth="md"
             >
-                <img src={dialogImg} alt="" />
+                <DialogContent
+                    style={{
```
Comment (MosheShlomi) [inline src/components/Chat/Chat.jsx:272]: set all the styles in scss file instead
