### PR TITLE
problem of sync when blocking the user fixed

### LINKED ISSUE #65: Fix sync problem on both sides when user block the chat

### PR DESCRIPTION
**Pull request by MosheShlomi**

### CODE REVIEW

File: src/lib/chatStore.js [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import { create } from "zustand";
 import { useUserStore } from "./userStore";
+import { arrayUnion, doc, getDoc, onSnapshot, updateDoc } from "firebase/firestore";
```
Comment (MosheShlomi) [inline src/lib/chatStore.js]: remove unused imports
