### PR TITLE
35 fixes in login and other components

### LINKED ISSUE #35: fixes in login and other components

### PR DESCRIPTION
**Pull request by MosheShlomi**

### CODE REVIEW

File: src/lib/userStore.js [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import { doc, getDoc, onSnapshot } from "firebase/firestore";
```
Comment (MosheShlomi) [inline src/lib/userStore.js]: remove unused imports
